[package]
name = "zbar-rs"
version = "0.1.0"
authors = ["Marcus Behrendt <marcus.behrendt@offis.de>"]
license = "LGPL 2.1"
description = "High-level rust bindings zo the zbar library"
keywords = ["bindings", "barcode reader"]
build = "build.rs"

[features]
default = ["from_image"]
from_image = ["image"]

[dependencies]
image = { version = "0.19.0", optional = true }

[dev-dependencies]
image = "0.19.0"
libc = "0.2.40"

[build-dependencies]
bindgen = "0.36.0"

[workspace]
