[package]
name = "zbar-rs"
version = "0.2.0-dev"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
license = "LGPL-2.1"
description = "High-level rust bindings zo the zbar library"
repository = "https://github.com/marhkb/zbar-rs.git"
readme = "README.md"
keywords = ["bindings", "ffi", "image", "library", "multimedia"]
categories = ["api-bindings", "multimedia", "multimedia::images", "external-ffi-bindings", ]
maintenance = { status = "experimental" }
build = "build.rs"

[features]
default = ["from_image"]
from_image = ["image"]

[dependencies]
image = { version = "0.19.0", optional = true }

[dev-dependencies]
image = "0.19.0"

[build-dependencies]
bindgen = "0.36.0"

[workspace]
